openapi: 3.0.0
info:
  title: Multi-Vendor eCommerce API
  description: Admin API for managing users, sellers, and sliders.
  version: 1.0.0
servers:
  - url: "http://localhost:5000"
    description: Local server

paths:
  /api/admin/users:
    get:
      summary: Get all users
      description: Retrieve all users in the system
      security:
        - BearerAuth: []
      responses:
        200:
          description: List of all users
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    userId:
                      type: string
                      example: "60adf6af5b4e1c001c1d66c8"
                    name:
                      type: string
                      example: "John Doe"
                    email:
                      type: string
                      example: "john.doe@example.com"
        403:
          description: Unauthorized access

  /api/admin/sellers:
    get:
      summary: Get all sellers
      description: Retrieve all sellers in the system
      security:
        - BearerAuth: []
      responses:
        200:
          description: List of all sellers
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sellerId:
                      type: string
                      example: "60adf6af5b4e1c001c1d66c8"
                    name:
                      type: string
                      example: "Seller A"
                    status:
                      type: string
                      example: "Pending"
        403:
          description: Unauthorized access

  /api/admin/approve-seller/{id}:
    put:
      summary: Approve a seller
      description: Approve a seller by ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the seller to approve
          schema:
            type: string
      responses:
        200:
          description: Seller approved successfully
        400:
          description: Invalid seller ID
        404:
          description: Seller not found

  /api/admin/reject-seller/{id}:
    delete:
      summary: Reject a seller
      description: Reject a seller by ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the seller to reject
          schema:
            type: string
      responses:
        200:
          description: Seller rejected successfully
        400:
          description: Invalid seller ID
        404:
          description: Seller not found

  /api/admin/sliders:
    get:
      summary: Get all sliders
      description: Retrieve all sliders from the system
      responses:
        200:
          description: List of all sliders
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    sliderId:
                      type: string
                      example: "60adf6af5b4e1c001c1d66c8"
                    imageUrl:
                      type: string
                      example: "http://example.com/slider.jpg"
                    description:
                      type: string
                      example: "Welcome to our store!"

  /api/admin/sliders/add:
    post:
      summary: Add a new slider
      description: Add a new slider to the system
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                imageUrl:
                  type: string
                  example: "http://example.com/new-slider.jpg"
                description:
                  type: string
                  example: "New product launch!"
      responses:
        201:
          description: Slider added successfully
        400:
          description: Invalid data provided

  /api/admin/sliders/{id}:
    delete:
      summary: Delete a slider
      description: Delete a slider by ID
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the slider to delete
          schema:
            type: string
      responses:
        200:
          description: Slider deleted successfully
        404:
          description: Slider not found
