openapi: 3.0.0
info:
  title: Multi-Vendor eCommerce API
  description: Cart API for managing customer cart operations.
  version: 1.0.0
servers:
  - url: "http://localhost:5000"
    description: Local server

paths:
  /api/cart/add:
    post:
      summary: Add product to cart
      description: Adds a product to the cart for a customer.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: string
                  example: "60adf6af5b4e1c001c1d66c8"
                productId:
                  type: string
                  example: "60adf6af5b4e1c001c1d66c9"
                quantity:
                  type: integer
                  example: 2
      responses:
        200:
          description: Product added to cart successfully
        400:
          description: Invalid request data

  /api/cart/{userId}:
    get:
      summary: Get user's cart
      description: Retrieves the cart for a specific customer by userId.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the customer whose cart to retrieve
          schema:
            type: string
      responses:
        200:
          description: Cart retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    productId:
                      type: string
                      example: "60adf6af5b4e1c001c1d66c9"
                    quantity:
                      type: integer
                      example: 2
        404:
          description: Cart not found

  /api/cart/update/{userId}/{productId}:
    put:
      summary: Update cart item
      description: Updates the quantity of a product in the cart.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the customer
          schema:
            type: string
        - name: productId
          in: path
          required: true
          description: ID of the product to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                quantity:
                  type: integer
                  example: 3
      responses:
        200:
          description: Cart item updated successfully
        400:
          description: Invalid request data
        404:
          description: Product not found

  /api/cart/remove/{userId}/{productId}:
    delete:
      summary: Remove product from cart
      description: Removes a specific product from the customer's cart.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the customer
          schema:
            type: string
        - name: productId
          in: path
          required: true
          description: ID of the product to remove
          schema:
            type: string
      responses:
        200:
          description: Product removed from cart successfully
        404:
          description: Product not found

  /api/cart/clear/{userId}:
    delete:
      summary: Clear the cart
      description: Clears all items from the customer's cart.
      parameters:
        - name: userId
          in: path
          required: true
          description: ID of the customer whose cart is to be cleared
          schema:
            type: string
      responses:
        200:
          description: Cart cleared successfully
        404:
          description: Cart not found
