openapi: 3.0.0
info:
  title: Multi-Vendor eCommerce API
  description: Customer API for registration, OTP verification, and user profile management.
  version: 1.0.0
servers:
  - url: "http://localhost:5000"
    description: Local server

paths:
  /api/users/register:
    post:
      summary: Register a new customer
      description: Registers a new customer by providing necessary details.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "John Doe"
                email:
                  type: string
                  example: "john.doe@example.com"
                password:
                  type: string
                  example: "password123"
                phone:
                  type: string
                  example: "1234567890"
      responses:
        201:
          description: Customer registered successfully
        400:
          description: Invalid input data

  /api/users/verify-otp:
    post:
      summary: Verify customer OTP
      description: Verifies the OTP sent to the customer's email or phone number.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  example: "123456"
                email:
                  type: string
                  example: "john.doe@example.com"
      responses:
        200:
          description: OTP verified successfully
        400:
          description: Invalid OTP

  /api/users/{id}:
    get:
      summary: Get customer details
      description: Retrieves the details of the customer by their ID.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the customer
          schema:
            type: string
      responses:
        200:
          description: Customer details retrieved successfully
        404:
          description: Customer not found

    put:
      summary: Update customer details
      description: Updates the customer profile information.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the customer to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "John Doe"
                email:
                  type: string
                  example: "john.doe@example.com"
                phone:
                  type: string
                  example: "1234567890"
      responses:
        200:
          description: Customer details updated successfully
        400:
          description: Invalid data
        404:
          description: Customer not found

    delete:
      summary: Delete customer account
      description: Deletes the customer account.
      parameters:
        - name: id
          in: path
          required: true
          description: ID of the customer to delete
          schema:
            type: string
      responses:
        200:
          description: Customer account deleted successfully
        404:
          description: Customer not found
