openapi: 3.0.0
info:
  title: Multi-Vendor eCommerce API
  description: Order API for order management, tracking, and status updates.
  version: 1.0.0
servers:
  - url: "http://localhost:5000"
    description: Local server

paths:
  /api/orders/checkout:
    post:
      summary: Checkout and place an order
      description: Initiates the checkout process and places an order for the customer.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                products:
                  type: array
                  items:
                    type: object
                    properties:
                      productId:
                        type: string
                        example: "productId123"
                      quantity:
                        type: integer
                        example: 2
                paymentMethod:
                  type: string
                  example: "credit card"
      responses:
        200:
          description: Order placed successfully
        400:
          description: Invalid input or payment failure

  /api/orders/update/{orderId}:
    put:
      summary: Update order status
      description: Updates the status of an order by the admin (e.g., Pending -> Shipped).
      parameters:
        - name: orderId
          in: path
          required: true
          description: The ID of the order to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  example: "shipped"
      responses:
        200:
          description: Order status updated successfully
        400:
          description: Invalid status or order not found

  /api/orders/track/{orderId}:
    get:
      summary: Track an order's status
      description: Retrieves the current status of an order.
      parameters:
        - name: orderId
          in: path
          required: true
          description: The ID of the order to track
          schema:
            type: string
      responses:
        200:
          description: Order status retrieved successfully
        404:
          description: Order not found

  /api/orders/all:
    get:
      summary: Get all orders
      description: Retrieves all orders for the admin.
      responses:
        200:
          description: List of all orders
        403:
          description: Unauthorized for non-admin users

  /api/orders/{orderId}:
    get:
      summary: Get order details
      description: Retrieves details of a specific order.
      parameters:
        - name: orderId
          in: path
          required: true
          description: The ID of the order to retrieve
          schema:
            type: string
      responses:
        200:
          description: Order details retrieved successfully
        404:
          description: Order not found

  /api/orders/user/{userId}/orders:
    get:
      summary: Get all orders by user
      description: Retrieves all orders placed by a specific customer.
      parameters:
        - name: userId
          in: path
          required: true
          description: The ID of the customer
          schema:
            type: string
      responses:
        200:
          description: List of orders placed by the user
        404:
          description: User not found