openapi: 3.0.0
info:
  title: Multi-Vendor eCommerce API
  description: Seller API for managing seller-related actions.
  version: 1.0.0
servers:
  - url: "http://localhost:5000"
    description: Local server

paths:
  /api/seller/register:
    post:
      summary: Register a new seller
      description: Allows a new seller to register and create an account.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "John Doe"
                email:
                  type: string
                  example: "john.doe@example.com"
                password:
                  type: string
                  example: "password123"
      responses:
        201:
          description: Seller registered successfully
        400:
          description: Invalid seller data

  /api/seller/verify-otp:
    post:
      summary: Verify seller OTP
      description: Allows a seller to verify the OTP during registration or login.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                otp:
                  type: string
                  example: "123456"
      responses:
        200:
          description: OTP verified successfully
        400:
          description: Invalid OTP

  /api/seller/{id}:
    get:
      summary: Get seller details by ID
      description: Retrieves the details of a specific seller by their ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the seller to retrieve
          schema:
            type: string
      responses:
        200:
          description: Seller details retrieved successfully
        404:
          description: Seller not found

    put:
      summary: Update seller details
      description: Allows the seller to update their profile details.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the seller to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "John Doe Updated"
                email:
                  type: string
                  example: "john.doe.updated@example.com"
                password:
                  type: string
                  example: "newpassword123"
      responses:
        200:
          description: Seller details updated successfully
        400:
          description: Invalid seller data

    delete:
      summary: Delete seller account
      description: Allows the seller to delete their account.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the seller to delete
          schema:
            type: string
      responses:
        200:
          description: Seller account deleted successfully
        404:
          description: Seller not found
